package com.juguito.juguitoreader.domain.model

data class EpubContent (
    val baseDir: String,
    val spine: List<String>,
    val chaptersTree: List<EpubNavElement>,
    val isIndexAutoGenerated: Boolean = false
)
